version: "3.3"

services:

  winbox:
    image: jeesa/winbox:latest-V4
    container_name: winbox
    restart: always
    ports:
      - "5901:5900"
      - "18081:8080"
    volumes:
      - /your/local/winbox-data:/home/winbox/.local/share/MikroTik/WinBox
    environment:
      - TZ=Asia/Shanghai
      - USERNAME='username'
      - PASSWORD='password'